### ISSUE TITLE
Do post writers need to attend the meeting?

### ISSUE THREAD

**Issue by shifwang** [rlbarter/Practical-Statistics#3]
I am Hue, I would like to participate but unfortunately my stat 133 office hour conflicts with the current schedule. Can I volunteer to be a post writer?

**Comment by rlbarter** [comment]
Sorry you can't make it Hue! 
I'm not opposed to the idea of absentee blog writers if there is an opening that hasn't been filled, but I think I'd prefer if the blog post authors actually can make the meetings so that they can capture the emphasis that we put on during our discussion and presentation.
What do others think?

**Comment by kellieotto** [comment]
Agreed with @rlbarter.  My understanding was that the blog post should be a more thorough treatment of the stuff in the presentation -- roughly the same content, but going into greater detail on examples/applications, extensions, and additional resources.

**Comment by shifwang** [comment]
Oh, got you! :)
